
CREATE TABLE [dbo].[LinkPrintTagged_Hyundai_01Jan26](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[article_id] [float] NULL,
	[incident_id] [float] NULL,
	[url] [nvarchar](1000) NULL,
	[title] [nvarchar](4000) NULL,
	[description] [nvarchar](max) NULL,
	[date_time] [nvarchar](255) NULL,
	[author] [nvarchar](255) NULL,
	[edition] [nvarchar](255) NULL,
	[page_no] [nvarchar](255) NULL,
	[sentiment] [nvarchar](255) NULL,
	[publication_name] [nvarchar](255) NULL,
	[publication_icon] [nvarchar](255) NULL,
	[publication_type] [nvarchar](255) NULL,
	[publication_category] [nvarchar](255) NULL,
	[publication_circulation] [nvarchar](255) NULL,
	[pi_score] [nvarchar](255) NULL,
	[ave] [nvarchar](255) NULL,
	[date_sort] [datetime] NULL,
	[circulation_sort] [float] NULL,
	[ave_sort] [float] NULL,
	[mention_type] [nvarchar](255) NULL,
	[is_bookmarked] [float] NULL,
	[headline_sentiment] [nvarchar](255) NULL,
	[pi_score_sort] [float] NULL,
	[Classifier_StockNews] [nvarchar](10) NULL,
	[Classifier_AlsoRead] [nvarchar](10) NULL,
	[Classifier_Reach_LessThan500] [nvarchar](10) NULL,
	[Classifier_Reach_MoreThan10000] [nvarchar](10) NULL,
	[Classifier_URL_ContentType] [nvarchar](50) NULL,
	[Classifier_TradeMedia] [nvarchar](10) NULL,
	[Classifier_Client_Hyundai] [nvarchar](10) NULL,
	[Classifier_Client_ProductMention] [nvarchar](10) NULL,
	[Classifier_OtherCompanies] [nvarchar](10) NULL,
	[Classifier_ScooterOnly] [nvarchar](10) NULL,
	[Classifier_Accident] [nvarchar](10) NULL,
	[Classifier_Review] [nvarchar](10) NULL,
	[Classifier_IPO] [varchar](3) NULL,
	[Classifier_Exports] [varchar](3) NULL,
	[Classifier_AutoExpo] [varchar](3) NULL,
	[Classifier_Launch] [varchar](3) NULL,
	[Classifier_ScooterBrands] [varchar](3) NULL,
	[Classifier_LuxuryBrands] [varchar](3) NULL,
	[Classifier_Festive] [varchar](3) NULL,
	[Classifier_Manufacture] [varchar](3) NULL,
	[Classifier_PreOwned] [varchar](3) NULL,
	[Classifier_SectorSpecific] [varchar](3) NULL,
	[Classifier_CompetitorProducts] [varchar](3) NULL,
	[Classifier_IsCompetitorSpokespersonMentioned] [varchar](3) NULL,
	[Classifier_IsNotRelevantDomain] [varchar](3) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO




CREATE TABLE [dbo].[LinkPrintTagged_KiaMotor_01Jan26](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[article_id] [float] NULL,
	[incident_id] [float] NULL,
	[url] [nvarchar](1000) NULL,
	[title] [nvarchar](1000) NULL,
	[description] [nvarchar](max) NULL,
	[date_time] [nvarchar](255) NULL,
	[author] [nvarchar](255) NULL,
	[edition] [nvarchar](255) NULL,
	[page_no] [nvarchar](255) NULL,
	[sentiment] [nvarchar](255) NULL,
	[publication_name] [nvarchar](255) NULL,
	[publication_icon] [nvarchar](255) NULL,
	[publication_type] [nvarchar](255) NULL,
	[publication_category] [nvarchar](255) NULL,
	[publication_circulation] [nvarchar](255) NULL,
	[pi_score] [nvarchar](255) NULL,
	[ave] [nvarchar](255) NULL,
	[date_sort] [datetime] NULL,
	[circulation_sort] [float] NULL,
	[ave_sort] [float] NULL,
	[mention_type] [nvarchar](255) NULL,
	[is_bookmarked] [float] NULL,
	[headline_sentiment] [nvarchar](255) NULL,
	[pi_score_sort] [float] NULL,
	[Classifier_StockNews] [nvarchar](10) NULL,
	[Classifier_AlsoRead] [nvarchar](10) NULL,
	[Classifier_Reach_LessThan500] [nvarchar](10) NULL,
	[Classifier_Reach_MoreThan10000] [nvarchar](10) NULL,
	[Classifier_URL_ContentType] [nvarchar](50) NULL,
	[Classifier_TradeMedia] [nvarchar](10) NULL,
	[Classifier_Client_KiaMotor] [nvarchar](10) NULL,
	[Classifier_Client_ProductMention] [nvarchar](10) NULL,
	[Classifier_OtherCompanies] [nvarchar](10) NULL,
	[Classifier_ScooterOnly] [nvarchar](10) NULL,
	[Classifier_Accident] [nvarchar](10) NULL,
	[Classifier_Review] [nvarchar](10) NULL,
	[Classifier_IPO] [varchar](3) NULL,
	[Classifier_Exports] [varchar](3) NULL,
	[Classifier_AutoExpo] [varchar](3) NULL,
	[Classifier_Launch] [varchar](3) NULL,
	[Classifier_ScooterBrands] [varchar](3) NULL,
	[Classifier_LuxuryBrands] [varchar](3) NULL,
	[Classifier_Festive] [varchar](3) NULL,
	[Classifier_Manufacture] [varchar](3) NULL,
	[Classifier_PreOwned] [varchar](3) NULL,
	[Classifier_SectorSpecific] [varchar](3) NULL,
	[Classifier_CompetitorProducts] [varchar](3) NULL,
	[Classifier_IsCompetitorSpokespersonMentioned] [varchar](3) NULL,
	[Classifier_IsNotRelevantDomain] [varchar](3) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



CREATE TABLE [dbo].[LinkPrintTagged_Mahindra_01Jan26](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[article_id] [float] NULL,
	[incident_id] [float] NULL,
	[url] [nvarchar](1000) NULL,
	[title] [nvarchar](3000) NULL,
	[description] [nvarchar](max) NULL,
	[date_time] [nvarchar](255) NULL,
	[author] [nvarchar](255) NULL,
	[edition] [nvarchar](255) NULL,
	[page_no] [nvarchar](255) NULL,
	[sentiment] [nvarchar](255) NULL,
	[publication_name] [nvarchar](255) NULL,
	[publication_icon] [nvarchar](255) NULL,
	[publication_type] [nvarchar](255) NULL,
	[publication_category] [nvarchar](255) NULL,
	[publication_circulation] [nvarchar](255) NULL,
	[pi_score] [nvarchar](255) NULL,
	[ave] [nvarchar](255) NULL,
	[date_sort] [datetime] NULL,
	[circulation_sort] [float] NULL,
	[ave_sort] [float] NULL,
	[mention_type] [nvarchar](255) NULL,
	[is_bookmarked] [float] NULL,
	[headline_sentiment] [nvarchar](255) NULL,
	[pi_score_sort] [float] NULL,
	[Classifier_StockNews] [nvarchar](10) NULL,
	[Classifier_AlsoRead] [nvarchar](10) NULL,
	[Classifier_Reach_LessThan500] [nvarchar](10) NULL,
	[Classifier_Reach_MoreThan10000] [nvarchar](10) NULL,
	[Classifier_URL_ContentType] [nvarchar](50) NULL,
	[Classifier_TradeMedia] [nvarchar](10) NULL,
	[Classifier_Client_Mahindra] [nvarchar](10) NULL,
	[Classifier_Client_ProductMention] [nvarchar](10) NULL,
	[Classifier_OtherCompanies] [nvarchar](10) NULL,
	[Classifier_ScooterOnly] [nvarchar](10) NULL,
	[Classifier_Accident] [nvarchar](10) NULL,
	[Classifier_Review] [nvarchar](10) NULL,
	[Classifier_IPO] [varchar](3) NULL,
	[Classifier_Exports] [varchar](3) NULL,
	[Classifier_AutoExpo] [varchar](3) NULL,
	[Classifier_Launch] [varchar](3) NULL,
	[Classifier_ScooterBrands] [varchar](3) NULL,
	[Classifier_LuxuryBrands] [varchar](3) NULL,
	[Classifier_Festive] [varchar](3) NULL,
	[Classifier_Manufacture] [varchar](3) NULL,
	[Classifier_PreOwned] [varchar](3) NULL,
	[Classifier_SectorSpecific] [varchar](3) NULL,
	[Classifier_CompetitorProducts] [varchar](3) NULL,
	[Classifier_IsCompetitorSpokespersonMentioned] [varchar](3) NULL,
	[Classifier_IsNotRelevantDomain] [varchar](3) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



CREATE TABLE [dbo].[LinkPrintTagged_MarutiSuzuki_01Jan26](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[article_id] [float] NULL,
	[incident_id] [float] NULL,
	[url] [nvarchar](1000) NULL,
	[title] [nvarchar](1000) NULL,
	[description] [nvarchar](max) NULL,
	[date_time] [nvarchar](255) NULL,
	[author] [nvarchar](255) NULL,
	[edition] [nvarchar](255) NULL,
	[page_no] [nvarchar](255) NULL,
	[sentiment] [nvarchar](255) NULL,
	[publication_name] [nvarchar](255) NULL,
	[publication_icon] [nvarchar](255) NULL,
	[publication_type] [nvarchar](255) NULL,
	[publication_category] [nvarchar](255) NULL,
	[publication_circulation] [nvarchar](255) NULL,
	[pi_score] [nvarchar](255) NULL,
	[ave] [nvarchar](255) NULL,
	[date_sort] [datetime] NULL,
	[circulation_sort] [float] NULL,
	[ave_sort] [float] NULL,
	[mention_type] [nvarchar](255) NULL,
	[is_bookmarked] [float] NULL,
	[headline_sentiment] [nvarchar](255) NULL,
	[pi_score_sort] [float] NULL,
	[Classifier_StockNews] [nvarchar](10) NULL,
	[Classifier_AlsoRead] [nvarchar](10) NULL,
	[Classifier_Reach_LessThan500] [nvarchar](10) NULL,
	[Classifier_Reach_MoreThan10000] [nvarchar](10) NULL,
	[Classifier_URL_ContentType] [nvarchar](50) NULL,
	[Classifier_TradeMedia] [nvarchar](10) NULL,
	[Classifier_Client_MarutiSuzuki] [nvarchar](10) NULL,
	[Classifier_Client_ProductMention] [nvarchar](10) NULL,
	[Classifier_OtherCompanies] [nvarchar](10) NULL,
	[Classifier_ScooterOnly] [nvarchar](10) NULL,
	[Classifier_Accident] [nvarchar](10) NULL,
	[Classifier_Review] [nvarchar](10) NULL,
	[Classifier_IPO] [varchar](3) NULL,
	[Classifier_Exports] [varchar](3) NULL,
	[Classifier_AutoExpo] [varchar](3) NULL,
	[Classifier_Launch] [varchar](3) NULL,
	[Classifier_ScooterBrands] [varchar](3) NULL,
	[Classifier_LuxuryBrands] [varchar](3) NULL,
	[Classifier_Festive] [varchar](3) NULL,
	[Classifier_Manufacture] [varchar](3) NULL,
	[Classifier_PreOwned] [varchar](3) NULL,
	[Classifier_SectorSpecific] [varchar](3) NULL,
	[Classifier_CompetitorProducts] [varchar](3) NULL,
	[Classifier_IsCompetitorSpokespersonMentioned] [varchar](3) NULL,
	[Classifier_IsNotRelevantDomain] [varchar](3) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



CREATE TABLE [dbo].[LinkPrintTagged_MGMotor_01Jan26](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[article_id] [float] NULL,
	[incident_id] [float] NULL,
	[url] [nvarchar](1000) NULL,
	[title] [nvarchar](1000) NULL,
	[description] [nvarchar](max) NULL,
	[date_time] [nvarchar](255) NULL,
	[author] [nvarchar](255) NULL,
	[edition] [nvarchar](255) NULL,
	[page_no] [nvarchar](255) NULL,
	[sentiment] [nvarchar](255) NULL,
	[publication_name] [nvarchar](255) NULL,
	[publication_icon] [nvarchar](255) NULL,
	[publication_type] [nvarchar](255) NULL,
	[publication_category] [nvarchar](255) NULL,
	[publication_circulation] [nvarchar](255) NULL,
	[pi_score] [nvarchar](255) NULL,
	[ave] [nvarchar](255) NULL,
	[date_sort] [datetime] NULL,
	[circulation_sort] [float] NULL,
	[ave_sort] [float] NULL,
	[mention_type] [nvarchar](255) NULL,
	[is_bookmarked] [float] NULL,
	[headline_sentiment] [nvarchar](255) NULL,
	[pi_score_sort] [float] NULL,
	[Classifier_StockNews] [nvarchar](10) NULL,
	[Classifier_AlsoRead] [nvarchar](10) NULL,
	[Classifier_Reach_LessThan500] [nvarchar](10) NULL,
	[Classifier_Reach_MoreThan10000] [nvarchar](10) NULL,
	[Classifier_URL_ContentType] [nvarchar](50) NULL,
	[Classifier_TradeMedia] [nvarchar](10) NULL,
	[Classifier_Client_MGMotor] [nvarchar](10) NULL,
	[Classifier_Client_ProductMention] [nvarchar](10) NULL,
	[Classifier_OtherCompanies] [nvarchar](10) NULL,
	[Classifier_ScooterOnly] [nvarchar](10) NULL,
	[Classifier_Accident] [nvarchar](10) NULL,
	[Classifier_Review] [nvarchar](10) NULL,
	[Classifier_IPO] [varchar](3) NULL,
	[Classifier_Exports] [varchar](3) NULL,
	[Classifier_AutoExpo] [varchar](3) NULL,
	[Classifier_Launch] [varchar](3) NULL,
	[Classifier_ScooterBrands] [varchar](3) NULL,
	[Classifier_LuxuryBrands] [varchar](3) NULL,
	[Classifier_Festive] [varchar](3) NULL,
	[Classifier_Manufacture] [varchar](3) NULL,
	[Classifier_PreOwned] [varchar](3) NULL,
	[Classifier_SectorSpecific] [varchar](3) NULL,
	[Classifier_CompetitorProducts] [varchar](3) NULL,
	[Classifier_IsCompetitorSpokespersonMentioned] [varchar](3) NULL,
	[Classifier_IsNotRelevantDomain] [varchar](3) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



CREATE TABLE [dbo].[LinkPrintTagged_TataMotors_01Jan26](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[article_id] [float] NULL,
	[incident_id] [float] NULL,
	[url] [nvarchar](1000) NULL,
	[title] [nvarchar](1000) NULL,
	[description] [nvarchar](max) NULL,
	[date_time] [nvarchar](255) NULL,
	[author] [nvarchar](255) NULL,
	[edition] [nvarchar](255) NULL,
	[page_no] [nvarchar](255) NULL,
	[sentiment] [nvarchar](255) NULL,
	[publication_name] [nvarchar](255) NULL,
	[publication_icon] [nvarchar](255) NULL,
	[publication_type] [nvarchar](255) NULL,
	[publication_category] [nvarchar](255) NULL,
	[publication_circulation] [nvarchar](255) NULL,
	[pi_score] [nvarchar](255) NULL,
	[ave] [nvarchar](255) NULL,
	[date_sort] [datetime] NULL,
	[circulation_sort] [float] NULL,
	[ave_sort] [float] NULL,
	[mention_type] [nvarchar](255) NULL,
	[is_bookmarked] [float] NULL,
	[headline_sentiment] [nvarchar](255) NULL,
	[pi_score_sort] [float] NULL,
	[Classifier_StockNews] [nvarchar](10) NULL,
	[Classifier_AlsoRead] [nvarchar](10) NULL,
	[Classifier_Reach_LessThan500] [nvarchar](10) NULL,
	[Classifier_Reach_MoreThan10000] [nvarchar](10) NULL,
	[Classifier_URL_ContentType] [nvarchar](50) NULL,
	[Classifier_TradeMedia] [nvarchar](10) NULL,
	[Classifier_Client_TataMotors] [nvarchar](10) NULL,
	[Classifier_Client_ProductMention] [nvarchar](10) NULL,
	[Classifier_Client_TataAutocomp] [nvarchar](10) NULL,
	[Classifier_OtherCompanies] [nvarchar](10) NULL,
	[Classifier_ScooterOnly] [nvarchar](10) NULL,
	[Classifier_Accident] [nvarchar](10) NULL,
	[Classifier_Review] [nvarchar](10) NULL,
	[Classifier_RatanTata] [nvarchar](10) NULL,
	[Classifier_IPO] [varchar](3) NULL,
	[Classifier_Exports] [varchar](3) NULL,
	[Classifier_AutoExpo] [varchar](3) NULL,
	[Classifier_Launch] [varchar](3) NULL,
	[Classifier_ScooterBrands] [varchar](3) NULL,
	[Classifier_LuxuryBrands] [varchar](3) NULL,
	[Classifier_Festive] [varchar](3) NULL,
	[Classifier_Manufacture] [varchar](3) NULL,
	[Classifier_PreOwned] [varchar](3) NULL,
	[Classifier_SectorSpecific] [varchar](3) NULL,
	[Classifier_CompetitorProducts] [varchar](3) NULL,
	[Classifier_IsCompetitorSpokespersonMentioned] [varchar](3) NULL,
	[Classifier_IsNotRelevantDomain] [varchar](3) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


