--drop table [LinkOnlineTagged_Hyundai_02Feb2026]
--drop table [LinkOnlineTagged_KiaMotor_02Feb2026]
--drop table [LinkOnlineTagged_Mahindra_02Feb2026]
--drop table [LinkOnlineTagged_MarutiSuzuki_02Feb2026]
--drop table [LinkOnlineTagged_MGMotor_02Feb2026]
--drop table [LinkOnlineTagged_TataMotors_02Feb2026]
select * from LinkOnlineTagged_Mahindra_02Feb2026

CREATE TABLE [dbo].[LinkOnlineTagged_Hyundai_02Feb2026](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[article_id] [float] NULL,
	[incident_id] [float] NULL,
	[url] [nvarchar](1000) NULL,
	[title] [nvarchar](4000) NULL,
	[description] [nvarchar](max) NULL,
	[date_time] [nvarchar](255) NULL,
	[author] [nvarchar](255) NULL,
	[sentiment] [nvarchar](255) NULL,
	[publication] [nvarchar](255) NULL,
	[publication_icon] [nvarchar](255) NULL,
	[publication_category] [nvarchar](255) NULL,
	[publication_type] [nvarchar](255) NULL,
	[publication_da] [nvarchar](255) NULL,
	[publication_traffic] [nvarchar](255) NULL,
	[pi_score] [nvarchar](255) NULL,
	[date_sort] [datetime] NULL,
	[da_sort] [float] NULL,
	[traffic_sort] [float] NULL,
	[pi_score_sort] [float] NULL,
	[mention_type] [nvarchar](255) NULL,
	[is_bookmarked] [float] NULL,
	[headline_sentiment] [nvarchar](255) NULL,
	[Classifier_StockNews] [nvarchar](10) NULL,
	[Classifier_AlsoRead] [nvarchar](10) NULL,
	[Classifier_Reach_LessThan500] [nvarchar](10) NULL,
	[Classifier_Reach_MoreThan10000] [nvarchar](10) NULL,
	[Classifier_URL_ContentType] [nvarchar](50) NULL,
	[Classifier_TradeMedia] [nvarchar](10) NULL,
	[Classifier_Client_Hyundai] [nvarchar](10) NULL,
	[Classifier_Client_ProductMention] [nvarchar](10) NULL,
	[Classifier_OtherCompanies] [nvarchar](10) NULL,
	[Classifier_ScooterOnly] [nvarchar](10) NULL,
	[Classifier_Accident] [nvarchar](10) NULL,
	[Classifier_Review] [nvarchar](10) NULL,
	[Classifier_IPO] [varchar](3) NULL,
	[Classifier_Exports] [varchar](3) NULL,
	[Classifier_AutoExpo] [varchar](3) NULL,
	[Classifier_Launch] [varchar](3) NULL,
	[Classifier_ScooterBrands] [varchar](3) NULL,
	[Classifier_LuxuryBrands] [varchar](3) NULL,
	[Classifier_Festive] [varchar](3) NULL,
	[Classifier_Manufacture] [varchar](3) NULL,
	[Classifier_PreOwned] [varchar](3) NULL,
	[Classifier_SectorSpecific] [varchar](3) NULL,
	[Classifier_CompetitorProducts] [varchar](3) NULL,
	[Classifier_IsNonNews] [varchar](5) NULL,
	[Classifier_IsCompetitorSpokespersonMentioned] [varchar](3) NULL,
	[Classifier_IsNotRelevantDomain] [varchar](3) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO




CREATE TABLE [dbo].[LinkOnlineTagged_KiaMotor_02Feb2026](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[article_id] [float] NULL,
	[incident_id] [float] NULL,
	[url] [nvarchar](1000) NULL,
	[title] [nvarchar](max) NULL,
	[description] [nvarchar](max) NULL,
	[date_time] [nvarchar](255) NULL,
	[author] [nvarchar](255) NULL,
	[sentiment] [nvarchar](255) NULL,
	[publication] [nvarchar](255) NULL,
	[publication_icon] [nvarchar](255) NULL,
	[publication_category] [nvarchar](255) NULL,
	[publication_type] [nvarchar](255) NULL,
	[publication_da] [nvarchar](255) NULL,
	[publication_traffic] [nvarchar](255) NULL,
	[pi_score] [nvarchar](255) NULL,
	[date_sort] [datetime] NULL,
	[da_sort] [float] NULL,
	[traffic_sort] [float] NULL,
	[pi_score_sort] [float] NULL,
	[mention_type] [nvarchar](255) NULL,
	[is_bookmarked] [float] NULL,
	[headline_sentiment] [nvarchar](255) NULL,
	[Classifier_StockNews] [nvarchar](10) NULL,
	[Classifier_AlsoRead] [nvarchar](10) NULL,
	[Classifier_Reach_LessThan500] [nvarchar](10) NULL,
	[Classifier_Reach_MoreThan10000] [nvarchar](10) NULL,
	[Classifier_URL_ContentType] [nvarchar](50) NULL,
	[Classifier_TradeMedia] [nvarchar](10) NULL,
	[Classifier_Client_KiaMotor] [nvarchar](10) NULL,
	[Classifier_Client_ProductMention] [nvarchar](10) NULL,
	[Classifier_OtherCompanies] [nvarchar](10) NULL,
	[Classifier_ScooterOnly] [nvarchar](10) NULL,
	[Classifier_Accident] [nvarchar](10) NULL,
	[Classifier_Review] [nvarchar](10) NULL,
	[Classifier_IPO] [varchar](3) NULL,
	[Classifier_Exports] [varchar](3) NULL,
	[Classifier_AutoExpo] [varchar](3) NULL,
	[Classifier_Launch] [varchar](3) NULL,
	[Classifier_ScooterBrands] [varchar](3) NULL,
	[Classifier_LuxuryBrands] [varchar](3) NULL,
	[Classifier_Festive] [varchar](3) NULL,
	[Classifier_Manufacture] [varchar](3) NULL,
	[Classifier_PreOwned] [varchar](3) NULL,
	[Classifier_SectorSpecific] [varchar](3) NULL,
	[Classifier_CompetitorProducts] [varchar](3) NULL,
	[Classifier_IsNonNews] [varchar](5) NULL,
	[Classifier_IsCompetitorSpokespersonMentioned] [varchar](3) NULL,
	[Classifier_IsNotRelevantDomain] [varchar](3) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



CREATE TABLE [dbo].[LinkOnlineTagged_Mahindra_02Feb2026](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[article_id] [float] NULL,
	[incident_id] [float] NULL,
	[url] [nvarchar](1000) NULL,
	[title] [nvarchar](MAX) NULL,
	[description] [nvarchar](max) NULL,
	[date_time] [nvarchar](255) NULL,
	[author] [nvarchar](255) NULL,
	[sentiment] [nvarchar](255) NULL,
	[publication] [nvarchar](255) NULL,
	[publication_icon] [nvarchar](255) NULL,
	[publication_category] [nvarchar](255) NULL,
	[publication_type] [nvarchar](255) NULL,
	[publication_da] [nvarchar](255) NULL,
	[publication_traffic] [nvarchar](255) NULL,
	[pi_score] [nvarchar](255) NULL,
	[date_sort] [datetime] NULL,
	[da_sort] [float] NULL,
	[traffic_sort] [float] NULL,
	[pi_score_sort] [float] NULL,
	[mention_type] [nvarchar](255) NULL,
	[is_bookmarked] [float] NULL,
	[headline_sentiment] [nvarchar](255) NULL,
	[Classifier_StockNews] [nvarchar](10) NULL,
	[Classifier_AlsoRead] [nvarchar](10) NULL,
	[Classifier_Reach_LessThan500] [nvarchar](10) NULL,
	[Classifier_Reach_MoreThan10000] [nvarchar](10) NULL,
	[Classifier_URL_ContentType] [nvarchar](50) NULL,
	[Classifier_TradeMedia] [nvarchar](10) NULL,
	[Classifier_Client_Mahindra] [nvarchar](10) NULL,
	[Classifier_Client_ProductMention] [nvarchar](10) NULL,
	[Classifier_OtherCompanies] [nvarchar](10) NULL,
	[Classifier_ScooterOnly] [nvarchar](10) NULL,
	[Classifier_Accident] [nvarchar](10) NULL,
	[Classifier_Review] [nvarchar](10) NULL,
	[Classifier_IPO] [varchar](3) NULL,
	[Classifier_Exports] [varchar](3) NULL,
	[Classifier_AutoExpo] [varchar](3) NULL,
	[Classifier_Launch] [varchar](3) NULL,
	[Classifier_ScooterBrands] [varchar](3) NULL,
	[Classifier_LuxuryBrands] [varchar](3) NULL,
	[Classifier_Festive] [varchar](3) NULL,
	[Classifier_Manufacture] [varchar](3) NULL,
	[Classifier_PreOwned] [varchar](3) NULL,
	[Classifier_SectorSpecific] [varchar](3) NULL,
	[Classifier_CompetitorProducts] [varchar](3) NULL,
	[Classifier_IsNonNews] [varchar](5) NULL,
	[Classifier_IsCompetitorSpokespersonMentioned] [varchar](3) NULL,
	[Classifier_IsNotRelevantDomain] [varchar](3) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



CREATE TABLE [dbo].[LinkOnlineTagged_MarutiSuzuki_02Feb2026](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[article_id] [float] NULL,
	[incident_id] [float] NULL,
	[url] [nvarchar](1000) NULL,
	[title] [nvarchar](1000) NULL,
	[description] [nvarchar](max) NULL,
	[date_time] [nvarchar](255) NULL,
	[author] [nvarchar](255) NULL,
	[sentiment] [nvarchar](255) NULL,
	[publication] [nvarchar](255) NULL,
	[publication_icon] [nvarchar](255) NULL,
	[publication_category] [nvarchar](255) NULL,
	[publication_type] [nvarchar](255) NULL,
	[publication_da] [nvarchar](255) NULL,
	[publication_traffic] [nvarchar](255) NULL,
	[pi_score] [nvarchar](255) NULL,
	[date_sort] [datetime] NULL,
	[da_sort] [float] NULL,
	[traffic_sort] [float] NULL,
	[pi_score_sort] [float] NULL,
	[mention_type] [nvarchar](255) NULL,
	[is_bookmarked] [float] NULL,
	[headline_sentiment] [nvarchar](255) NULL,
	[Classifier_StockNews] [nvarchar](10) NULL,
	[Classifier_AlsoRead] [nvarchar](10) NULL,
	[Classifier_Reach_LessThan500] [nvarchar](10) NULL,
	[Classifier_Reach_MoreThan10000] [nvarchar](10) NULL,
	[Classifier_URL_ContentType] [nvarchar](50) NULL,
	[Classifier_TradeMedia] [nvarchar](10) NULL,
	[Classifier_Client_MarutiSuzuki] [nvarchar](10) NULL,
	[Classifier_Client_ProductMention] [nvarchar](10) NULL,
	[Classifier_OtherCompanies] [nvarchar](10) NULL,
	[Classifier_ScooterOnly] [nvarchar](10) NULL,
	[Classifier_Accident] [nvarchar](10) NULL,
	[Classifier_Review] [nvarchar](10) NULL,
	[Classifier_IPO] [varchar](3) NULL,
	[Classifier_Exports] [varchar](3) NULL,
	[Classifier_AutoExpo] [varchar](3) NULL,
	[Classifier_Launch] [varchar](3) NULL,
	[Classifier_ScooterBrands] [varchar](3) NULL,
	[Classifier_LuxuryBrands] [varchar](3) NULL,
	[Classifier_Festive] [varchar](3) NULL,
	[Classifier_Manufacture] [varchar](3) NULL,
	[Classifier_PreOwned] [varchar](3) NULL,
	[Classifier_SectorSpecific] [varchar](3) NULL,
	[Classifier_CompetitorProducts] [varchar](3) NULL,
	[Classifier_IsNonNews] [varchar](5) NULL,
	[Classifier_IsCompetitorSpokespersonMentioned] [varchar](3) NULL,
	[Classifier_IsNotRelevantDomain] [varchar](3) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO




CREATE TABLE [dbo].[LinkOnlineTagged_MGMotor_02Feb2026](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[article_id] [float] NULL,
	[incident_id] [float] NULL,
	[url] [nvarchar](1000) NULL,
	[title] [nvarchar](4000) NULL,
	[description] [nvarchar](max) NULL,
	[date_time] [nvarchar](255) NULL,
	[author] [nvarchar](255) NULL,
	[sentiment] [nvarchar](255) NULL,
	[publication] [nvarchar](255) NULL,
	[publication_icon] [nvarchar](255) NULL,
	[publication_category] [nvarchar](255) NULL,
	[publication_type] [nvarchar](255) NULL,
	[publication_da] [nvarchar](255) NULL,
	[publication_traffic] [nvarchar](255) NULL,
	[pi_score] [nvarchar](255) NULL,
	[date_sort] [datetime] NULL,
	[da_sort] [float] NULL,
	[traffic_sort] [float] NULL,
	[pi_score_sort] [float] NULL,
	[mention_type] [nvarchar](255) NULL,
	[is_bookmarked] [float] NULL,
	[headline_sentiment] [nvarchar](255) NULL,
	[Classifier_StockNews] [nvarchar](10) NULL,
	[Classifier_AlsoRead] [nvarchar](10) NULL,
	[Classifier_Reach_LessThan500] [nvarchar](10) NULL,
	[Classifier_Reach_MoreThan10000] [nvarchar](10) NULL,
	[Classifier_URL_ContentType] [nvarchar](50) NULL,
	[Classifier_TradeMedia] [nvarchar](10) NULL,
	[Classifier_Client_MGMotor] [nvarchar](10) NULL,
	[Classifier_Client_ProductMention] [nvarchar](10) NULL,
	[Classifier_OtherCompanies] [nvarchar](10) NULL,
	[Classifier_ScooterOnly] [nvarchar](10) NULL,
	[Classifier_Accident] [nvarchar](10) NULL,
	[Classifier_Review] [nvarchar](10) NULL,
	[Classifier_IPO] [varchar](3) NULL,
	[Classifier_Exports] [varchar](3) NULL,
	[Classifier_AutoExpo] [varchar](3) NULL,
	[Classifier_Launch] [varchar](3) NULL,
	[Classifier_ScooterBrands] [varchar](3) NULL,
	[Classifier_LuxuryBrands] [varchar](3) NULL,
	[Classifier_Festive] [varchar](3) NULL,
	[Classifier_Manufacture] [varchar](3) NULL,
	[Classifier_PreOwned] [varchar](3) NULL,
	[Classifier_SectorSpecific] [varchar](3) NULL,
	[Classifier_CompetitorProducts] [varchar](3) NULL,
	[Classifier_IsNonNews] [varchar](5) NULL,
	[Classifier_IsCompetitorSpokespersonMentioned] [varchar](3) NULL,
	[Classifier_IsNotRelevantDomain] [varchar](3) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



CREATE TABLE [dbo].[LinkOnlineTagged_TataMotors_02Feb2026](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[article_id] [float] NULL,
	[incident_id] [float] NULL,
	[url] [nvarchar](1000) NULL,
	[title] [nvarchar](4000) NULL,
	[description] [nvarchar](max) NULL,
	[date_time] [nvarchar](255) NULL,
	[author] [nvarchar](255) NULL,
	[sentiment] [nvarchar](255) NULL,
	[publication] [nvarchar](255) NULL,
	[publication_icon] [nvarchar](255) NULL,
	[publication_category] [nvarchar](255) NULL,
	[publication_type] [nvarchar](255) NULL,
	[publication_da] [nvarchar](255) NULL,
	[publication_traffic] [nvarchar](255) NULL,
	[pi_score] [nvarchar](255) NULL,
	[date_sort] [datetime] NULL,
	[da_sort] [float] NULL,
	[traffic_sort] [float] NULL,
	[pi_score_sort] [float] NULL,
	[mention_type] [nvarchar](255) NULL,
	[is_bookmarked] [float] NULL,
	[headline_sentiment] [nvarchar](255) NULL,
	[Classifier_StockNews] [nvarchar](10) NULL,
	[Classifier_AlsoRead] [nvarchar](10) NULL,
	[Classifier_Reach_LessThan500] [nvarchar](10) NULL,
	[Classifier_Reach_MoreThan10000] [nvarchar](10) NULL,
	[Classifier_URL_ContentType] [nvarchar](50) NULL,
	[Classifier_TradeMedia] [nvarchar](10) NULL,
	[Classifier_Client_TataMotors] [nvarchar](10) NULL,
	[Classifier_Client_ProductMention] [nvarchar](10) NULL,
	[Classifier_Client_TataAutocomp] [nvarchar](10) NULL,
	[Classifier_OtherCompanies] [nvarchar](10) NULL,
	[Classifier_ScooterOnly] [nvarchar](10) NULL,
	[Classifier_Accident] [nvarchar](10) NULL,
	[Classifier_Review] [nvarchar](10) NULL,
	[Classifier_RatanTata] [nvarchar](10) NULL,
	[Classifier_IPO] [varchar](3) NULL,
	[Classifier_Exports] [varchar](3) NULL,
	[Classifier_AutoExpo] [varchar](3) NULL,
	[Classifier_Launch] [varchar](3) NULL,
	[Classifier_ScooterBrands] [varchar](3) NULL,
	[Classifier_LuxuryBrands] [varchar](3) NULL,
	[Classifier_Festive] [varchar](3) NULL,
	[Classifier_Manufacture] [varchar](3) NULL,
	[Classifier_PreOwned] [varchar](3) NULL,
	[Classifier_SectorSpecific] [varchar](3) NULL,
	[Classifier_CompetitorProducts] [varchar](3) NULL,
	[Classifier_IsNonNews] [varchar](5) NULL,
	[Classifier_IsCompetitorSpokespersonMentioned] [varchar](3) NULL,
	[Classifier_IsNotRelevantDomain] [varchar](3) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


